# SOME DESCRIPTIVE TITLE.
# Copyright (C) 2022-2025, PyMC Labs
# This file is distributed under the same license as the pymc-marketing
# package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2025.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: pymc-marketing local\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2025-10-07 18:10+0300\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: es <LL@li.org>\n"
"Language: es\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"Generated-By: Babel 2.17.0\n"

#: ../source/api/generated/classmethods/pymc_marketing.mmm.hsgp.HSGP.__init__.rst:2
#: bc22fa0d566b45e59e949c1954dd1fa8
msgid "HSGP.\\_\\_init\\_\\_"
msgstr "HSGP.\\_\\_init\\_\\_"

#: 19485b7e292540688145e0554ff93d02 of pydantic.main.BaseModel.__init__:2
msgid ""
"Create a new model by parsing and validating input data from keyword "
"arguments."
msgstr ""
"Cree un nuevo modelo analizando y validando los datos de entrada de los "
"argumentos de palabras clave."

#: 84ef9f5b38114492aff2af72f2267da3 of pydantic.main.BaseModel.__init__:4
msgid ""
"Raises [`ValidationError`][pydantic_core.ValidationError] if the input data "
"cannot be validated to form a valid model."
msgstr ""
"Genera [`ValidationError`][pydantic_core.ValidationError] si los datos de "
"entrada no pueden ser validados para formar un modelo válido."

#: 1e1b1d7e67af49039be6d898cc836392 of pydantic.main.BaseModel.__init__:7
msgid "`self` is explicitly positional-only to allow `self` as a field name."
msgstr ""
"`self` es explícitamente solo posicional para permitir que `self` sea un "
"nombre de campo."
